### ISSUE TITLE
Questions about the data format of c3d files

### ISSUE THREAD

**Issue by zsh2000** [abcyzj/ChoreoNet#2]
Hi,

Thanks for sharing the data and I find myself interested in your work. But I'm a little puzzled on the data format of c3d files.

I download the c3d file and use the package "c3d" in Python to read the file. I find it contains an array of shape (5298, 41, 5). (take 8.c3d as an example) Also, the last two elements of dimension 2 is all zero. (See in the picture above, take frame 1827 as an example) 

So I am wondering how the data is related to the quaternion-based joint rotation representation in your paper.

Best regards,
Shuhong
<img width="464" alt="微信截图_20210629203244" src="https://user-images.githubusercontent.com/52485301/123798244-93157980-d919-11eb-82a0-662a9e002dd6.png">

**Comment by abcyzj** [comment]
The shape (5298, 41, 5) corresponds to 5298 frames of 41 joints. The last two elements of dimension 2 can be ignored, the first 3 elements represents Euclidean coordinates of the joints. You can read the label of each joint from the c3d file using https://github.com/pyomeca/ezc3d, the labels for the 41 joints are as follows:
```python
['LFHD', 'RFHD', 'LBHD', 'RBHD', 'C7', 'T10', 'CLAV', 'STRN', 'RBAC', 'LSHO', 'LUPA', 'LELB', 'LFRM', 'LWRA', 'LWRB', 'LFIN', 'RSHO', 'RUPA', 'RELB', 'RFRM', 'RWRA', 'RWRB', 'RFIN', 'LFWT', 'RFWT', 'LBWT', 'RBWT', 'LTHI', 'LKNE', 'LSHN', 'LANK', 'LHEE', 'LTOE', 'LMT5', 'RTHI', 'RKNE', 'RSHN', 'RANK', 'RHEE', 'RTOE', 'RMT5']
```
This picture gives an illustration of these joints:
![5053438-6816724722e2643f](https://user-images.githubusercontent.com/26025487/123801135-8fcfbd00-d91c-11eb-91db-8ce99b5d87c9.PNG)
Having obtained the Euclidean coordinates of the joints, you can conduct inverse kinematics to get the quaternion of each joint.

**Comment by zsh2000** [comment]
Thanks so much for your quick reply! I'll try it!

**Comment by zsh2000** [comment]
Thanks again @abcyzj,

Now I'm trying reproducing your work, but I come across some problems.

1. The music of "DANCE_C_1" is about 211 seconds long, with the CAU sequences starting at frame 395 and ending at frame 4350. The music of "DANCE_C_6" is about 238 seconds long, with the CAU sequences starting at frame 18 and ending at frame 1923.

    Does this mean that for some pieces of music, the corresponding dance will have an "end-of-dance (EOD)" occuring too early? This means leaving a large portion of music empty with no dance.


2. When using "librosa" to detect beat, we need to assign a sample rate (sr = 22050 by default). Different sample rate will cause different output of detected beats. So I am wondering how to assign the sample rate when using "librosa".


Best regards,
Shuhong
